/**
 * 主题状态管理 - 通用主题系统
 * 提供明暗主题切换功能，支持 localStorage 持久化
 * 默认使用暗色模式
 */
import { defineStore } from 'pinia'
import { ref, watch } from 'vue'

export const useThemeStore = defineStore('theme', () => {
  // 默认暗色模式
  const isDark = ref(true)

  const toggleTheme = () => {
    isDark.value = !isDark.value
    updateCssVariables(isDark.value)
  }

  const setTheme = (dark: boolean) => {
    isDark.value = dark
    updateCssVariables(isDark.value)
  }

  // 监听主题变化，持久化到 localStorage
  watch(isDark, (newVal) => {
    localStorage.setItem('angineer-theme', newVal ? 'dark' : 'light')
    updateCssVariables(newVal)
  })

  // 更新全局 CSS 变量和 html 类名
  const updateCssVariables = (dark: boolean) => {
    const root = document.documentElement
    if (dark) {
      root.classList.add('dark')
      root.classList.remove('light')
      root.style.setProperty('--bg-primary', '#141414')
      root.style.setProperty('--bg-secondary', '#1f1f1f')
      root.style.setProperty('--bg-tertiary', '#272727')
      root.style.setProperty('--text-primary', 'rgba(255, 255, 255, 0.85)')
      root.style.setProperty('--text-secondary', 'rgba(255, 255, 255, 0.65)')
      root.style.setProperty('--text-tertiary', 'rgba(255, 255, 255, 0.45)')
      root.style.setProperty('--border-color', '#303030')
      root.style.setProperty('--divider-color', 'rgba(255, 255, 255, 0.12)')
      // 独立包（table-ui SectionCard 等）的卡片底/阴影：宿主必须提供，否则回退白色
      root.style.setProperty('--card-bg', '#1f1f1f')
      root.style.setProperty('--shadow-sm', '0 1px 2px rgba(0, 0, 0, 0.4)')
      root.style.setProperty('--shadow-md', '0 4px 12px rgba(0, 0, 0, 0.5)')
      root.style.setProperty('--panel-bg', '#1f1f1f')
      root.style.setProperty('--panel-header-bg', '#272727')
      root.style.setProperty('--panel-header-divider', '#4d4d4d')
      root.style.setProperty('--chat-root-bg', '#000000')
      root.style.setProperty('--tree-bg', '#000000')
      root.style.setProperty('--docs-bg', '#141414')
      root.style.setProperty('--docs-pane-bg', '#1f1f1f')
      root.style.setProperty('--docs-pane-border', '#303030')
      root.style.setProperty('--docs-title-bg', '#1f1f1f')
      root.style.setProperty('--docs-title-border', '#303030')
      root.style.setProperty('--docs-text', 'rgba(255, 255, 255, 0.78)')
      root.style.setProperty('--docs-text-strong', 'rgba(255, 255, 255, 0.92)')
      root.style.setProperty('--docs-text-subtle', 'rgba(255, 255, 255, 0.62)')
      root.style.setProperty('--docs-progress-bg', '#1f1f1f')
      root.style.setProperty('--docs-content-bg', '#1f1f1f')
      root.style.setProperty('--docs-code-bg', '#1d2330')
      root.style.setProperty('--docs-inline-code-bg', 'rgba(255, 255, 255, 0.12)')
      root.style.setProperty('--docs-index-card-bg', '#1d2330')
      root.style.setProperty('--docs-empty-overlay', 'rgba(20, 20, 20, 0.92)')
      root.style.setProperty('--docs-empty-text', 'rgba(255, 255, 255, 0.6)')
      root.style.setProperty('--docs-segment-bg', '#2a3345')
      root.style.setProperty('--docs-segment-border', '#38445b')
      root.style.setProperty('--docs-segment-selected-bg', '#3a4660')
      root.style.setProperty('--docs-segment-selected-text', 'rgba(255, 255, 255, 0.9)')
      root.style.setProperty('--docs-segment-shared-bg', 'linear-gradient(90deg, #49aa19 0%, #237804 100%)')
      root.style.setProperty('--docs-segment-shared-border', '#237804')
      root.style.setProperty('--docs-math-bg', 'rgba(59, 130, 246, 0.18)')
      root.style.setProperty('--docs-math-color', 'rgba(219, 234, 254, 0.95)')
      root.style.setProperty('--chip-default-border', '#1e3a8a')
      root.style.setProperty('--chip-default-bg', '#1e293b')
      root.style.setProperty('--chip-default-text', '#93c5fd')
      root.style.setProperty('--chip-lv-border', '#581c87')
      root.style.setProperty('--chip-lv-bg', '#2e1065')
      root.style.setProperty('--chip-lv-text', '#c4b5fd')
      root.style.setProperty('--chip-pos-border', '#7c2d12')
      root.style.setProperty('--chip-pos-bg', '#431407')
      root.style.setProperty('--chip-pos-text', '#fdba74')
      root.style.setProperty('--chat-user-bubble-bg', '#1677ff')
      root.style.setProperty('--chat-user-bubble-text', '#fff')
      root.style.setProperty('--chat-assistant-bubble-bg', '#2a2a2a')
      root.style.setProperty('--chat-assistant-bubble-text', 'rgba(255,255,255,0.85)')
      root.style.setProperty('--chat-code-bg', 'rgba(255,255,255,0.1)')
      root.style.setProperty('--chat-pre-bg', '#1d2330')
      root.style.setProperty('--chat-citation-bg', 'rgba(250,173,20,0.08)')
      root.style.setProperty('--chat-citation-accent', '#ffc53d')
      root.style.setProperty('--chat-streaming-cursor', '#4096ff')
      root.style.setProperty('--chat-streaming-bg', 'rgba(24,144,255,0.08)')
      root.style.setProperty('--chat-system-bg', 'rgba(250,173,20,0.1)')
      root.style.setProperty('--chat-system-text', '#ffc53d')
      root.style.setProperty('--chat-system-border', 'rgba(250,173,20,0.3)')
      root.style.setProperty('--chat-citation-border', '#ffc53d')
      root.style.setProperty('--chat-error-color', '#ff7875')
      root.style.setProperty('--chat-error-hover', '#ffa39e')
      root.style.setProperty('--chat-success-color', '#73d13d')
      root.style.setProperty('--primary-color', '#1890ff')
      root.style.setProperty('--tree-drop-zone-bg', 'rgba(24,144,255,0.08)')
      root.style.setProperty('--tree-folder-color', '#faad14')
      root.style.setProperty('--tree-markdown-color', '#13c2c2')
      root.style.setProperty('--tree-danger-color', '#ff7875')
      root.style.setProperty('--tree-danger-hover', '#ff4d4f')
      root.style.setProperty('--tree-drop-border', '#91caff')
      root.style.setProperty('--graph-root-bg', '#ddd6fe')
      root.style.setProperty('--graph-root-border', '#7c3aed')
      root.style.setProperty('--graph-expanded-bg', '#bfdbfe')
      root.style.setProperty('--graph-expanded-border', '#2563eb')
      root.style.setProperty('--graph-collapsed-bg', '#fef3c7')
      root.style.setProperty('--graph-collapsed-border', '#f59e0b')
      root.style.setProperty('--graph-leaf-bg', '#e5e7eb')
      root.style.setProperty('--graph-leaf-border', '#6b7280')
      root.style.setProperty('--dp-pane-border', '#38445b')
      root.style.setProperty('--dp-index-card-bg', '#1d2330')
      root.style.setProperty('--dp-sub-text', 'rgba(255,255,255,0.55)')
      root.style.setProperty('--dp-title-text', 'rgba(255,255,255,0.85)')
      root.style.setProperty('--dp-title-strong', 'rgba(255,255,255,0.92)')
      root.style.setProperty('--dp-content-bg', '#1a1f2e')
      root.style.setProperty('--dp-pane-bg', '#1f1f2e')
      root.style.setProperty('--dp-hover-border', 'rgba(24,144,255,0.35)')
      root.style.setProperty('--dp-hover-bg', 'rgba(24,144,255,0.06)')
      root.style.setProperty('--dp-active-border', 'rgba(24,144,255,0.6)')
      root.style.setProperty('--dp-active-shadow', 'rgba(24,144,255,0.2)')
      root.style.setProperty('--dp-active-bg', 'rgba(24,144,255,0.1)')
      root.style.setProperty('--dp-children-border', 'rgba(255,255,255,0.1)')
      root.style.setProperty('--dp-inline-media-bg', 'rgba(255,255,255,0.04)')
      root.style.setProperty('--dp-surface-bg', 'rgba(255,255,255,0.03)')
      root.style.setProperty('--dp-badge-bg', 'rgba(37,99,235,0.18)')
      root.style.setProperty('--dp-badge-border', 'rgba(96,165,250,0.3)')
      root.style.setProperty('--dp-badge-text', '#93c5fd')
      root.style.setProperty('--dp-badge-active-bg', 'rgba(37,99,235,0.22)')
      root.style.setProperty('--dp-badge-active-border', 'rgba(96,165,250,0.4)')
      root.style.setProperty('--dp-badge-active-text', '#93c5fd')
      root.style.setProperty('--dp-tag-bg', 'rgba(37,99,235,0.15)')
      root.style.setProperty('--dp-tag-border', 'rgba(96,165,250,0.3)')
      root.style.setProperty('--dp-tag-active-bg', 'rgba(37,99,235,0.22)')
      root.style.setProperty('--dp-tag-active-border', 'rgba(96,165,250,0.4)')
      root.style.setProperty('--dp-tag-active-text', '#93c5fd')
      root.style.setProperty('--dp-warning-bg', 'rgba(120,53,15,0.18)')
      root.style.setProperty('--dp-warning-border', 'rgba(245,158,11,0.3)')
      root.style.setProperty('--dp-warning-title', '#fbbf24')
      root.style.setProperty('--dp-warning-text', '#fcd34d')
      root.style.setProperty('--dp-hint-bg', 'rgba(37,99,235,0.18)')
      root.style.setProperty('--dp-hint-border', 'rgba(59,130,246,0.3)')
      root.style.setProperty('--brand-gradient-start', '#818cf8')
      root.style.setProperty('--brand-gradient-end', '#a855f7')
      root.style.setProperty('--fork-border', '#7c6200')
      root.style.setProperty('--fork-bg', '#2b2500')
    } else {
      root.classList.remove('dark')
      root.classList.add('light')
      root.style.setProperty('--bg-primary', '#f0f2f5')
      root.style.setProperty('--bg-secondary', '#ffffff')
      root.style.setProperty('--bg-tertiary', '#fafafa')
      root.style.setProperty('--text-primary', 'rgba(0, 0, 0, 0.88)')
      root.style.setProperty('--text-secondary', 'rgba(0, 0, 0, 0.65)')
      root.style.setProperty('--text-tertiary', 'rgba(0, 0, 0, 0.45)')
      root.style.setProperty('--border-color', '#e8e8e8')
      root.style.setProperty('--divider-color', 'rgba(0, 0, 0, 0.08)')
      root.style.setProperty('--card-bg', '#ffffff')
      root.style.setProperty('--shadow-sm', '0 1px 2px rgba(0, 0, 0, 0.06)')
      root.style.setProperty('--shadow-md', '0 4px 12px rgba(0, 0, 0, 0.08)')
      root.style.setProperty('--panel-bg', '#ffffff')
      root.style.setProperty('--panel-header-bg', '#fafafa')
      root.style.setProperty('--panel-header-divider', '#e0e0e0')
      root.style.setProperty('--chat-root-bg', '#f0f2f5')
      root.style.setProperty('--tree-bg', '#ffffff')
      root.style.setProperty('--docs-bg', '#f0f2f5')
      root.style.setProperty('--docs-pane-bg', '#ffffff')
      root.style.setProperty('--docs-pane-border', '#e8edf4')
      root.style.setProperty('--docs-title-bg', '#ffffff')
      root.style.setProperty('--docs-title-border', '#edf1f7')
      root.style.setProperty('--docs-text', '#595959')
      root.style.setProperty('--docs-text-strong', '#4f5d7a')
      root.style.setProperty('--docs-text-subtle', '#8c8c8c')
      root.style.setProperty('--docs-progress-bg', '#f7f9fc')
      root.style.setProperty('--docs-content-bg', '#ffffff')
      root.style.setProperty('--docs-code-bg', '#f6f8fa')
      root.style.setProperty('--docs-inline-code-bg', 'rgba(0, 0, 0, 0.04)')
      root.style.setProperty('--docs-index-card-bg', '#fafcff')
      root.style.setProperty('--docs-empty-overlay', 'rgba(255, 255, 255, 0.92)')
      root.style.setProperty('--docs-empty-text', 'rgba(0, 0, 0, 0.45)')
      root.style.setProperty('--docs-segment-bg', '#dfe5f2')
      root.style.setProperty('--docs-segment-border', '#cdd6e7')
      root.style.setProperty('--docs-segment-selected-bg', '#ffffff')
      root.style.setProperty('--docs-segment-selected-text', '#1f2937')
      root.style.setProperty('--docs-segment-shared-bg', 'linear-gradient(90deg, #52c41a 0%, #389e0d 100%)')
      root.style.setProperty('--docs-segment-shared-border', '#389e0d')
      root.style.setProperty('--docs-math-bg', '#eef3ff')
      root.style.setProperty('--docs-math-color', '#1d3a8a')
      root.style.setProperty('--chip-default-border', '#dbeafe')
      root.style.setProperty('--chip-default-bg', '#eff6ff')
      root.style.setProperty('--chip-default-text', '#1d4ed8')
      root.style.setProperty('--chip-lv-border', '#e9d5ff')
      root.style.setProperty('--chip-lv-bg', '#faf5ff')
      root.style.setProperty('--chip-lv-text', '#7e22ce')
      root.style.setProperty('--chip-pos-border', '#fed7aa')
      root.style.setProperty('--chip-pos-bg', '#fff7ed')
      root.style.setProperty('--chip-pos-text', '#9a3412')
      root.style.setProperty('--chat-user-bubble-bg', '#1890ff')
      root.style.setProperty('--chat-user-bubble-text', '#fff')
      root.style.setProperty('--chat-assistant-bubble-bg', '#f5f5f5')
      root.style.setProperty('--chat-assistant-bubble-text', '#333')
      root.style.setProperty('--chat-code-bg', '#e8e8e8')
      root.style.setProperty('--chat-pre-bg', '#f0f0f0')
      root.style.setProperty('--chat-citation-bg', '#fffaf0')
      root.style.setProperty('--chat-citation-accent', '#ad6800')
      root.style.setProperty('--chat-streaming-cursor', '#1890ff')
      root.style.setProperty('--chat-streaming-bg', '#e6f7ff')
      root.style.setProperty('--chat-system-bg', '#fff7e6')
      root.style.setProperty('--chat-system-text', '#d46b08')
      root.style.setProperty('--chat-system-border', '#ffd591')
      root.style.setProperty('--chat-citation-border', '#faad14')
      root.style.setProperty('--chat-error-color', '#ff4d4f')
      root.style.setProperty('--chat-error-hover', '#ff7875')
      root.style.setProperty('--chat-success-color', '#52c41a')
      root.style.setProperty('--primary-color', '#1890ff')
      root.style.setProperty('--tree-drop-zone-bg', '#f0f8ff')
      root.style.setProperty('--tree-folder-color', '#faad14')
      root.style.setProperty('--tree-markdown-color', '#13c2c2')
      root.style.setProperty('--tree-danger-color', '#ff4d4f')
      root.style.setProperty('--tree-danger-hover', '#ff7875')
      root.style.setProperty('--tree-drop-border', '#91caff')
      root.style.setProperty('--graph-root-bg', '#ddd6fe')
      root.style.setProperty('--graph-root-border', '#7c3aed')
      root.style.setProperty('--graph-expanded-bg', '#bfdbfe')
      root.style.setProperty('--graph-expanded-border', '#2563eb')
      root.style.setProperty('--graph-collapsed-bg', '#fef3c7')
      root.style.setProperty('--graph-collapsed-border', '#f59e0b')
      root.style.setProperty('--graph-leaf-bg', '#e5e7eb')
      root.style.setProperty('--graph-leaf-border', '#6b7280')
      root.style.setProperty('--dp-pane-border', '#e2e8f0')
      root.style.setProperty('--dp-index-card-bg', '#ffffff')
      root.style.setProperty('--dp-sub-text', '#64748b')
      root.style.setProperty('--dp-title-text', '#0f172a')
      root.style.setProperty('--dp-title-strong', '#0f172a')
      root.style.setProperty('--dp-content-bg', '#ffffff')
      root.style.setProperty('--dp-pane-bg', '#ffffff')
      root.style.setProperty('--dp-hover-border', '#bfdbfe')
      root.style.setProperty('--dp-hover-bg', '#f0f5ff')
      root.style.setProperty('--dp-active-border', 'rgba(22,119,255,0.8)')
      root.style.setProperty('--dp-active-shadow', 'rgba(22,119,255,0.14)')
      root.style.setProperty('--dp-active-bg', '#e6f0ff')
      root.style.setProperty('--dp-children-border', '#cbd5e1')
      root.style.setProperty('--dp-inline-media-bg', '#f5f7fc')
      root.style.setProperty('--dp-surface-bg', '#f8fafc')
      root.style.setProperty('--dp-badge-bg', '#f1f5f9')
      root.style.setProperty('--dp-badge-border', 'rgba(148,163,184,0.2)')
      root.style.setProperty('--dp-badge-text', '#0f172a')
      root.style.setProperty('--dp-badge-active-bg', '#dbeafe')
      root.style.setProperty('--dp-badge-active-border', 'rgba(37,99,235,0.2)')
      root.style.setProperty('--dp-badge-active-text', '#1d4ed8')
      root.style.setProperty('--dp-tag-bg', '#eef2f7')
      root.style.setProperty('--dp-tag-border', '#d5dbe6')
      root.style.setProperty('--dp-tag-active-bg', '#dbeafe')
      root.style.setProperty('--dp-tag-active-border', 'rgba(37,99,235,0.2)')
      root.style.setProperty('--dp-tag-active-text', '#1d4ed8')
      root.style.setProperty('--dp-warning-bg', '#fef3c7')
      root.style.setProperty('--dp-warning-border', 'rgba(245,158,11,0.28)')
      root.style.setProperty('--dp-warning-title', '#b45309')
      root.style.setProperty('--dp-warning-text', '#92400e')
      root.style.setProperty('--dp-hint-bg', '#dbeafe')
      root.style.setProperty('--dp-hint-border', 'rgba(59,130,246,0.22)')
      root.style.setProperty('--brand-gradient-start', '#818cf8')
      root.style.setProperty('--brand-gradient-end', '#a855f7')
      root.style.setProperty('--fork-border', '#faad14')
      root.style.setProperty('--fork-bg', '#fffbe6')
    }
  }

  const initTheme = () => {
    const savedTheme = localStorage.getItem('angineer-theme')
    if (savedTheme) {
      isDark.value = savedTheme === 'dark'
    } else {
      // 默认暗色模式
      isDark.value = true
    }
    updateCssVariables(isDark.value)
  }

  return {
    isDark,
    toggleTheme,
    setTheme,
    initTheme
  }
})
